### ISSUE TITLE
can't run learn test or learn submit

### ISSUE THREAD

**Issue by Ahmed-aleryani** [learn-co-curriculum/fewpjs-stitching-together-the-three-pillars-new#3]
this lab has an issue which says  Traceback (most recent call last):
        11: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in`<main>'
        10: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in`eval'
         9: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-test:23:in `<main>'
         8: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-test:23:in `load'
         7: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/bin/learn-test:68:in `<top (required)>'
         6: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `run'
         5: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `fork'
         4: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:21:in `block in run'
         3: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:44:in `report_and_clean'
         2: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:13:in `report'
         1: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:47:in `report'
/usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by Ahmed-aleryani** [comment]
Well i have been trying to fix this issue, i ran npm audit fix. I tried many solutions, then when i tried to go to online environment the issue was there as well. can you please check this issue because when i tried running learn submit it worked, but learn test still not working.

**Comment by lizbur10** [comment]
Hi Ahmed! I'm so sorry to hear that you're having problems! 

I am not able to reproduce the issue which means it is likely the result of an issue with your development environment. I suggest that you post a question on [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson). The technical coaches can help you troubleshoot the issue. 

Thanks! 💙
