### ISSUE TITLE
All steps already done/ nothing to do in this lab

### ISSUE THREAD

**Issue by AmilMasic** [learn-co-curriculum/fewpjs-stitching-together-the-three-pillars-new#5]
All of the code that we are supposed to uncomment is already uncommented. The tests pass by doing nothing.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been addressed. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
