### ISSUE TITLE
Non-working README LAB

### ISSUE THREAD

**Issue by kristenkinnearohlmann** [learn-co-curriculum/fewpjs-stitching-together-the-three-pillars-new#7]
I worked with an AAQ coach and they agreed this was not working. All of the code was already uncommented and trying to submit through learn submit repeatedly failed.

I am running Windows 10 WSL 2.

**Comment by graciemcguire** [comment]
Hi there,

Would you mind providing a bit more detail about the issue? Things that are especially useful:
- An expanded explanation of what's going on.
- Steps to reproduce the issue.
- A [stack trace](https://en.wikipedia.org/wiki/Stack_trace) of any errors.

Thanks! 💙
